import type { Project } from '@/types/content';

export const projects: Project[] = [
  {
    slug: 'recruiter-signal-dashboard',
    title: 'Recruiter Signal Dashboard',
    tagline: 'A hiring workflow dashboard that turns noisy candidate activity into readable recruiting signals.',
    summary: 'Designed and implemented a dashboard for recruiters to prioritize candidate follow-up, identify funnel bottlenecks, and explain weekly hiring movement.',
    role: 'Frontend Architect / Product Analyst',
    team: 'Solo prototype with simulated backend data',
    duration: '6 weeks',
    stack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Motion', 'Recharts', 'Zod'],
    problem: 'Recruiting teams often scan fragmented spreadsheets, notes, and ATS exports. The decision problem is not “show more charts”; it is “which candidates and stages need attention now?”',
    constraints: [
      'Recruiters need fast scanning, not a dense BI dashboard.',
      'Metrics must be explainable to hiring managers.',
      'Prototype had to work with static anonymized data and be deployable on Vercel.',
    ],
    process: [
      'Mapped the recruiting funnel into attention states: stalled, warming, ready, risky.',
      'Designed low-fidelity layouts around weekly standup questions.',
      'Created typed mock data and reusable metric card components.',
      'Validated the information hierarchy with a five-minute scan test.',
    ],
    architecture: [
      'App Router pages for dashboard, candidate detail, and weekly summary.',
      'Static content layer for demo data with typed selectors.',
      'Component primitives for metric cards, status ribbons, and comparison charts.',
      'Progressive enhancement for animations; content remains readable without JavaScript motion.',
    ],
    solution: [
      'Prioritized a “next best action” panel above secondary analytics.',
      'Used stage-level anomaly callouts instead of decorative chart grids.',
      'Added compact candidate cards with evidence snippets and risk labels.',
    ],
    outcome: 'The prototype demonstrates a recruiter-first analytics flow: attention, evidence, action. It is intentionally lightweight and easy to adapt to a real ATS integration.',
    metrics: [
      { label: 'Scan path', value: '3 steps', note: 'From overview to next action.' },
      { label: 'Prototype data', value: '120 rows', note: 'Synthetic candidate events.' },
      { label: 'Lighthouse target', value: '95+ A11y', note: 'Accessible dashboard baseline.' },
    ],
    reflection: 'The strongest product decision was removing charts that did not change recruiter behavior. The next iteration should connect to real ATS event streams and run a task-based usability test.',
    links: [
      { label: 'Demo', href: 'https://example.com/demo' },
      { label: 'Repository', href: 'https://github.com/yourname/recruiter-signal-dashboard' },
    ],
    coverImage: '/project-covers/recruiter-signal.svg',
    theme: { accent: '#9f2d20', accent2: '#d7a647', paper: '#f6efe2', ink: '#17130f', pattern: 'grid' },
    featured: true,
  },
  {
    slug: 'visual-analytics-briefing-room',
    title: 'Visual Analytics Briefing Room',
    tagline: 'An editorial data story template for explaining product movement with fewer, stronger charts.',
    summary: 'A Quarto-inspired web briefing format for teams that need to explain trends, not just display dashboards.',
    role: 'Design Engineer / Data Storyteller',
    team: 'Research-led solo build',
    duration: '4 weeks',
    stack: ['R', 'Quarto', 'D3.js', 'Next.js', 'TypeScript'],
    problem: 'Stakeholders often receive dashboards without narrative framing. The result is more metrics but less confidence in decisions.',
    constraints: [
      'Must support dense evidence while remaining readable.',
      'Charts need captions, caveats, and decision implications.',
      'Should be exportable as a static web artifact.',
    ],
    process: [
      'Audited dashboard screenshots to identify repeated low-value visuals.',
      'Defined a briefing page grammar: claim, evidence, caveat, action.',
      'Built reusable chart explanation blocks and annotation styles.',
      'Tested the page on mobile to avoid horizontal-scroll dependence.',
    ],
    architecture: [
      'Static report pages generated from structured content sections.',
      'Chart modules isolated from narrative blocks.',
      'CSS variables for theme swaps between paper and dark editorial modes.',
    ],
    solution: [
      'Used fewer charts with stronger written claims.',
      'Added visual “evidence cards” for assumptions and limitations.',
      'Created a table-of-contents rail for fast executive scanning.',
    ],
    outcome: 'The artifact turns exploratory analysis into a decision-ready briefing that product managers can circulate asynchronously.',
    metrics: [
      { label: 'Chart count', value: '-45%', note: 'Reduced repeated visuals.' },
      { label: 'Reading time', value: '7 min', note: 'Executive summary format.' },
      { label: 'Sections', value: '6', note: 'Claim-driven structure.' },
    ],
    reflection: 'The project reinforced that visual analytics is a writing problem as much as a charting problem. The next step is an authoring CLI for report scaffolds.',
    links: [{ label: 'Case notes', href: 'https://example.com/briefing-room' }],
    coverImage: '/project-covers/briefing-room.svg',
    theme: { accent: '#244f8f', accent2: '#b94f6a', paper: '#f4f0e8', ink: '#111827', pattern: 'scan' },
    featured: true,
  },
  {
    slug: 'campus-product-lab',
    title: 'Campus Product Lab',
    tagline: 'A small product operating system for student teams: roadmap, feedback, experiments, and launch notes.',
    summary: 'Designed a collaborative workspace that helps student builders move from idea to testable product with explicit decision records.',
    role: 'Full-stack Developer / Product Lead',
    team: '3 student builders',
    duration: '8 weeks',
    stack: ['Next.js', 'PostgreSQL', 'Prisma', 'NextAuth', 'Tailwind CSS'],
    problem: 'Student teams usually lose product context across chats, docs, and slides. Roadmap decisions become hard to audit.',
    constraints: [
      'Small team with limited backend maintenance capacity.',
      'Need familiar UI patterns for non-technical teammates.',
      'Privacy-sensitive feedback notes must be clearly scoped.',
    ],
    process: [
      'Interviewed student project leads about their weekly planning pain points.',
      'Prioritized experiment tracking over broad task management.',
      'Designed simple roles, project spaces, and decision logs.',
      'Ran a two-week pilot with one capstone-style team.',
    ],
    architecture: [
      'Server components for core project views.',
      'PostgreSQL schema for teams, experiments, feedback, and decisions.',
      'Minimal API routes for mutations and audit history.',
      'Auth boundary around team workspaces.',
    ],
    solution: [
      'Created an experiment board with hypothesis, signal, owner, and result fields.',
      'Added feedback clustering for repeated user pain points.',
      'Generated weekly launch-note summaries from structured updates.',
    ],
    outcome: 'The prototype helped a student team keep decisions visible and reduced repeated “why did we choose this?” discussions.',
    metrics: [
      { label: 'Pilot team', value: '1', note: 'Two-week usage test.' },
      { label: 'Decision logs', value: '24', note: 'Recorded during pilot.' },
      { label: 'Setup time', value: '<10 min', note: 'Project onboarding target.' },
    ],
    reflection: 'A narrow product OS beats a generic task tracker when the target user has a specific cadence. The next version should improve notifications and integration with GitHub Projects.',
    links: [{ label: 'Prototype', href: 'https://example.com/campus-product-lab' }],
    coverImage: '/project-covers/campus-lab.svg',
    theme: { accent: '#3c6f4a', accent2: '#c46b2c', paper: '#f7f1df', ink: '#151815', pattern: 'ribbon' },
    featured: true,
  },
  {
    slug: 'privacy-first-notes',
    title: 'Privacy-first Notes Companion',
    tagline: 'A local-first note intelligence prototype with transparent retrieval and citation-first answers.',
    summary: 'Explored how students can query personal study notes while keeping source references visible and editable.',
    role: 'Prototype Engineer',
    team: 'Solo',
    duration: '3 weeks',
    stack: ['Python', 'SQLite', 'React', 'Embeddings', 'Local LLM'],
    problem: 'Note assistants become untrustworthy when they hide where answers come from or over-summarize uncertain material.',
    constraints: [
      'Must work with local files and degraded model availability.',
      'Every generated answer needs visible citations.',
      'UI should encourage source review, not blind acceptance.',
    ],
    process: [
      'Defined answer states: cited, partial, uncertain, unsupported.',
      'Built a local ingestion prototype with chunk metadata.',
      'Designed citation cards and source preview interactions.',
    ],
    architecture: [
      'Local SQLite store for document metadata and chunks.',
      'Retrieval layer separated from answer-generation layer.',
      'React interface for query, answer, citations, and source review.',
    ],
    solution: [
      'Displayed answer confidence as evidence coverage, not a fake percentage.',
      'Added quick filters for notes, lectures, and assignments.',
      'Made citations first-class UI elements with direct source snippets.',
    ],
    outcome: 'The prototype demonstrates a safer pattern for personal knowledge assistants: answers are useful only when the evidence path is visible.',
    metrics: [
      { label: 'Local docs', value: '80+', note: 'Prototype test corpus.' },
      { label: 'Citation coverage', value: '100%', note: 'Required for answer display.' },
      { label: 'Cloud dependency', value: '0', note: 'Local-first mode.' },
    ],
    reflection: 'The design challenge is trust calibration. Future work should test how users handle conflicting notes and stale source material.',
    links: [{ label: 'Write-up', href: 'https://example.com/privacy-first-notes' }],
    coverImage: '/project-covers/privacy-notes.svg',
    theme: { accent: '#6b4aa0', accent2: '#2e718c', paper: '#f3eadc', ink: '#15111d', pattern: 'dots' },
  },
];
